repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-merge-conflict
    - id: mixed-line-ending
      args: [--fix=crlf]

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black

# - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
#   rev: v1.3.1
#   hooks:
#     - id: python-safety-dependencies-check
#       files: pyproject.toml

- repo: https://github.com/timothycrosley/isort
  rev: 5.13.2
  hooks:
    - id: isort
